'use strict';
const fs=require('fs');const path=require('path');
const {SafeError}=require('../runtime');
const {roots,sha256Buffer,sha256File,listPackageDirs}=require('./common');
const {readEvents}=require('../companion/job-store');

function validateCompanionRelease(manifest){if(!manifest.companion_job_id)return manifest;let events;try{events=readEvents(manifest.companion_job_id);}catch{throw new SafeError('Companion-Freigabenachweis fehlt oder ist ungültig.');}const released=events[events.length-1];if(released.state!=='Released'||released.output_sha256!==manifest.document_sha256)throw new SafeError('Companion-Paket ist nicht atomar freigegeben.');return manifest;}
function readManifest(dir){try{return validateCompanionRelease(JSON.parse(fs.readFileSync(path.join(dir,'manifest.json'),'utf8')));}catch(e){if(e instanceof SafeError)throw e;throw new SafeError('Paketmanifest fehlt oder ist ungültig.');}}
function safeResolvePackage(id){const r=roots(),name=path.basename(String(id||''));if(!name||name!==String(id||'')||name.startsWith('.'))throw new SafeError('Ungültige Paket-ID.');const p=path.join(r.output,name);if(!fs.existsSync(p))throw new SafeError('Paket nicht gefunden.');const st=fs.lstatSync(p);if(st.isSymbolicLink()||!st.isDirectory())throw new SafeError('Paketpfad ist nicht freigegeben.');const real=fs.realpathSync(p),base=fs.realpathSync(r.output)+path.sep;if(!real.startsWith(base))throw new SafeError('Paket außerhalb des Output-Bereichs.');const m=readManifest(p);if(m.package_id!==name)throw new SafeError('Paket-ID/Manifest stimmen nicht überein.');return{p,m};}
function safeFile(base,rel){const f=path.join(base,rel);if(!fs.existsSync(f))throw new SafeError('Paketdatei fehlt.');const st=fs.lstatSync(f);if(st.isSymbolicLink()||!st.isFile())throw new SafeError('Paketdatei ist nicht freigegeben.');const rp=fs.realpathSync(f),br=fs.realpathSync(base)+path.sep;if(!rp.startsWith(br))throw new SafeError('Paketdatei außerhalb des Pakets.');return f;}
function listOutputs(){const items=[];for(const x of listPackageDirs()){try{const m=readManifest(x.full);items.push({package_id:x.id,profile:m.profile,created_at:m.created_at,reidentification_risk:m.reidentification_risk,assets_included:(m.assets||[]).filter(a=>a.status==='included').length,assets_review_required:(m.assets||[]).filter(a=>a.status!=='included').length});}catch{}}return{ok:true,packages:items.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,50)};}
function readOutput(packageId,offset=0,maxChars=16000){const{p,m}=safeResolvePackage(packageId),rel=path.basename(String(m.document||''));if(!rel||rel!==m.document)throw new SafeError('Ungültiger Dokumentpfad.');const f=safeFile(p,rel);if(m.document_sha256&&sha256File(f)!==m.document_sha256)throw new SafeError('Anonymisierte Markdown-Datei wurde verändert.');const text=fs.readFileSync(f,'utf8');offset=Math.max(0,Number(offset)||0);maxChars=Math.min(30000,Math.max(1000,Number(maxChars)||16000));return{ok:true,package_id:packageId,document_id:rel,offset,text:text.slice(offset,offset+maxChars),next_offset:Math.min(text.length,offset+maxChars),has_more:offset+maxChars<text.length,total_chars:text.length,content_is_verified_anonymized_markdown:true};}
function listAssets(packageId){const{m}=safeResolvePackage(packageId);return{ok:true,package_id:packageId,assets:(m.assets||[]).filter(a=>a.status==='included').map(a=>({asset_id:a.asset_id,file:a.file,mime_type:a.output_mime,bytes:a.bytes,redactions:a.redactions||0}))};}
function readAsset(packageId,assetId){const{p,m}=safeResolvePackage(packageId),a=(m.assets||[]).find(x=>x.status==='included'&&x.asset_id===assetId);if(!a)throw new SafeError('Sicheres Asset nicht gefunden.');const rel=String(a.file||'');if(!/^assets\/[^/]+$/.test(rel))throw new SafeError('Ungültiger Assetpfad.');const f=safeFile(p,rel.split('/').join(path.sep)),data=fs.readFileSync(f);if(a.sha256&&sha256Buffer(data)!==a.sha256)throw new SafeError('Asset wurde nach Freigabe verändert.');return{ok:true,package_id:packageId,asset_id:assetId,mime_type:a.output_mime,bytes:data.length,__image:{data:data.toString('base64'),mimeType:a.output_mime}};}

module.exports={readManifest,safeResolvePackage,safeFile,listOutputs,readOutput,listAssets,readAsset};
