'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');
const {SafeError}=require('../runtime');
const pii=require('../pii-engine');
const {VERSION,roots,sha256File,uniquePath}=require('./common');

function anonymizeMarkdown(raw,profile){let pass=1,r=pii.anonymize(raw,profile),candidate=r.text,total=r.findings.length,res=pii.scanResidual(candidate,profile);if(res.length){const r2=pii.anonymize(candidate,profile);candidate=r2.text;total+=r2.findings.length;pass=2;res=pii.scanResidual(candidate,profile);}if(res.length){throw new SafeError(`Finale Rest-PII-Prüfung hat ${res.length} mögliche direkte Identifikatoren gefunden. Verarbeitung wurde fail-closed gestoppt.`);}return{text:candidate,entityCount:total,passes:pass,reidentificationRisk:r.reidentification_risk};}
function complianceHeader(profile,meta){let ai='Die AI-Act-Risikoklasse hängt vom nachgelagerten Verwendungszweck ab; Privacy-Verarbeitung ist keine Konformitätszertifizierung.';if(profile==='applicant')ai='Bewerberanalyse/-filterung/-bewertung für Auswahlentscheidungen kann Annex III Beschäftigung betreffen. Kein automatisches Ranking oder Entscheiden ohne freigegebenen Governance-Prozess.';if(profile==='personnel_profile')ai='Bei Beschäftigten können insbesondere Bewertung, Beförderung, Kündigung, Überwachung oder bestimmte auf Verhalten/Persönlichkeitsmerkmalen basierende Aufgabenzuweisungen Annex III betreffen. Kompetenzbeschreibung allein ist nicht automatisch High-Risk; Zweck separat klassifizieren.';return`<!--\nEU Privacy Document Gateway ${VERSION}\nProfil: ${profile}\nQuelle: ${meta.ext.slice(1).toUpperCase()}\nRest-PII-Prüfung: bestanden\nDatenschutz-Pässe: ${meta.passes}\nErsetzte/erfasste Identifikatoren: ${meta.entityCount}\nAutomatisch freigegebene visuelle Assets: ${meta.included}\nLokale visuelle Review-Items: ${meta.review}\nPersistente Rückzuordnung: nein\nRe-Identifikationsrisiko: ${meta.reidentificationRisk}\nHinweis: De-Identifizierung garantiert keine rechtliche Anonymität.\nEU AI Act: ${ai}\n-->\n\n`;}
function aiActMeta(profile){if(profile==='applicant')return{employment_annex_iii_possible:true,prohibit_unapproved_ranking:true,human_oversight_governance_required_for_high_risk_use:true};if(profile==='personnel_profile')return{employment_annex_iii_possible_for_evaluation_promotion_termination_monitoring_or_certain_task_allocation:true,descriptive_skill_profile_not_automatically_high_risk:true,downstream_purpose_classification_required:true};return{downstream_purpose_classification_required:true};}
function auditRecord(profile,source,md,meta){return{timestamp:new Date().toISOString(),gateway_version:VERSION,profile,source_extension:path.extname(source).toLowerCase(),source_sha256:sha256File(source),source_bytes:fs.statSync(source).size,output_sha256:sha256File(md),text_entity_count:meta.entityCount,privacy_passes:meta.passes,residual_pii_verification:'passed',reidentification_risk:meta.reidentificationRisk,visual_assets_total:meta.results.length,visual_assets_included:meta.results.filter(x=>x.status==='included').length,visual_assets_review_required:meta.results.filter(x=>x.status!=='included').length,visual_redactions:meta.results.reduce((n,x)=>n+(x.redactions||0),0),raw_content_logged:false,mapping_retained:false,ai_act:aiActMeta(profile)};}
function writeAudit(rec,dir){const r=roots();const global=path.join(r.audit,`audit_${Date.now()}_${crypto.randomBytes(3).toString('hex')}.json`);fs.writeFileSync(global,JSON.stringify(rec,null,2),'utf8');fs.writeFileSync(path.join(dir,'audit.json'),JSON.stringify(rec,null,2),'utf8');}
function moveProcessed(source){const r=roots(),d=uniquePath(r.processed,path.basename(source));try{fs.renameSync(source,d);}catch{fs.copyFileSync(source,d);fs.unlinkSync(source);}}

module.exports={anonymizeMarkdown,complianceHeader,aiActMeta,auditRecord,writeAudit,moveProcessed};
