'use strict';
const {SafeError}=require('./runtime');
const {roots,openFolder,detectProfileFromMarkdown,safePackageId}=require('./gateway/common');
const {genericStatus}=require('./gateway/status');
const {anonymizeNext,anonymizeAll,anonymizeSelectedSource}=require('./gateway/orchestrator');
const {listOutputs,issueReadCapability,requireReadCapability,readOutput,listAssets,readAsset}=require('./gateway/package-store');
const {listReviewItems,approveReviewAsset}=require('./gateway/review');
const {prepareVisual,processVisuals}=require('./gateway/visuals');
const {anonymizeMarkdown}=require('./gateway/compliance');
const {cleanupLocalData,retentionStatus,purgeLocalData}=require('./gateway/retention');
const {diagnosticStatus}=require('./gateway/diagnostics');
const {beginBatch,processBatchNext,recoverBatches}=require('./gateway/batch');
module.exports={SafeError,roots,genericStatus,diagnosticStatus,openFolder,anonymizeNext,anonymizeAll,beginBatch,processBatchNext,recoverBatches,listOutputs,issueReadCapability,requireReadCapability,readOutput,listAssets,readAsset,listReviewItems,approveReviewAsset,cleanupLocalData,retentionStatus,purgeLocalData,_internal:{anonymizeSelectedSource},_test:{detectProfileFromMarkdown,safePackageId,prepareVisual,anonymizeMarkdown,processVisuals}};
