'use strict';
const {SafeError}=require('./runtime');
const {roots,openFolder,detectProfileFromMarkdown,safePackageId}=require('./gateway/common');
const {genericStatus}=require('./gateway/status');
const {anonymizeNext}=require('./gateway/orchestrator');
const {listOutputs,readOutput,listAssets,readAsset}=require('./gateway/package-store');
const {listReviewItems,approveReviewAsset}=require('./gateway/review');
const {prepareVisual,processVisuals}=require('./gateway/visuals');
const {anonymizeMarkdown}=require('./gateway/compliance');
module.exports={SafeError,roots,genericStatus,openFolder,anonymizeNext,listOutputs,readOutput,listAssets,readAsset,listReviewItems,approveReviewAsset,_test:{detectProfileFromMarkdown,safePackageId,prepareVisual,anonymizeMarkdown,processVisuals}};
